spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Configuration pour l'envoi d'emails (exemple avec Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: yassir12hasbi@gmail.com
    password: VOTRE_MOT_DE_PASSE_D_APPLICATION
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/